name: automatic build
on:
  push:
    tags-ignore:
      - ref/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: cargo build --release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: cargo install
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path collectors/ --root output
      - name: package
        shell: bash
        run: |
          tar zcvf collectors.tar.gz -C output/ .
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: false
          draft: false
      - name: Upload Assets
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: collectors.tar.gz
          asset_name: collectors.tar.gz

